In [2]:
import numpy as np
import torch

In [9]:
x = torch.randn(3, requires_grad=True)
x

tensor([-1.3447,  0.2682, -1.9219], requires_grad=True)

In [10]:
y = x+2
y

tensor([0.6553, 2.2682, 0.0781], grad_fn=<AddBackward0>)

In [11]:
z = y*y*2
z

tensor([ 0.8590, 10.2891,  0.0122], grad_fn=<MulBackward0>)

In [12]:
z = z.mean()
z

tensor(3.7201, grad_fn=<MeanBackward0>)

In [13]:
z.backward()

In [14]:
x.grad

tensor([0.8738, 3.0242, 0.1042])

In [15]:
x.requires_grad_(False)
x

tensor([-1.3447,  0.2682, -1.9219])

In [18]:
y = x.detach()
y

tensor([-1.3447,  0.2682, -1.9219])

In [19]:
with torch.no_grad():
    y = x+2
    print(y)

tensor([0.6553, 2.2682, 0.0781])


In [24]:
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
  model_output = (weights*3).sum()

  model_output.backward()

  print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [23]:
weights.grad.zero_()

tensor([0., 0., 0., 0.])

In [25]:
optimizer = torch.optim.SGD(weights, lr=0.01)
optimizer.step()
optimizer.zero_grad()

TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor